### ISSUE TITLE
Does not work in Python 3.11

### ISSUE THREAD

**Issue by nyggus** [nyggus/perftester#16]
It seems that the version of `memory_profiler` used does not work with Python 3.11. What to do with that?

**Comment by nyggus** [comment]
Works - needed to change the version of `memory_profiler`.

**Comment by singularitti** [comment]
I met the same problem. Which version of `memory_profiler` should I change to?

**Comment by singularitti** [comment]
Thanks for your reply, I think it's probably of the Python environment on macOS.
`memory_profiler` [v0.61.0 are said to be solving this problem](https://github.com/pythonprofilers/memory_profiler/issues/375#issuecomment-1317653743).
I'm looking into [this answer](https://stackoverflow.com/a/67465708) and this [comment](https://github.com/asdf-community/asdf-python/issues/50#issuecomment-1771503362) to see if they work.

**Comment by nyggus** [comment]
Please let us know whether it works!

**Comment by singularitti** [comment]
Sure!
